# Generated by Django 4.1.6 on 2023-02-10 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_type', models.CharField(max_length=50)),
                ('image_url', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=50)),
                ('condition', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('purpose', models.CharField(max_length=50)),
                ('theme', models.CharField(max_length=50)),
                ('mood', models.CharField(max_length=50)),
                ('deadline', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cozynestapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='PieceStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cozynestapi.piece')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cozynestapi.style')),
            ],
        ),
        migrations.AddField(
            model_name='piece',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cozynestapi.room'),
        ),
        migrations.AddField(
            model_name='piece',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cozynestapi.user'),
        ),
    ]
